version: '3.8'

services:
  python:
    build: .
    container_name: sigma-coding-trading-bot
    ports:
      - 8080:8080
    volumes:
      - ./:/app
  
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - 5000:5000